gcc -I. -I./ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -I/home/praneet/ffmpeg_build/include -gstabs+ -std=c++11 -pthread  -I/home/praneet/ffmpeg_build/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/freetype2  -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/opus         -DZMQ_BUILD_DRAFT_API=1 -I/usr/local/include -I/usr/include/alsa     -g3 -Wdeclaration-after-statement -Wall -Wdisabled-optimization -Wpointer-arith -Wredundant-decls -Wwrite-strings -Wtype-limits -Wundef -Wmissing-prototypes -Wno-pointer-to-int-cast -Wstrict-prototypes -Wempty-body -Wno-parentheses -Wno-switch -Wno-format-zero-length -Wno-pointer-sign  -fno-math-errno -fno-signed-zeros -fno-tree-vectorize -Werror=format-security -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=vla -Wformat -fdiagnostics-color=auto -Wno-maybe-uninitialized -Wl,-rpath-link=libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample \-D_REENTRANT -I/usr/include/SDL2 -I /usr/include/python3.5m   -MMD -MF fftools/ffmpeg.d -MT fftools/ffmpeg.o -c -shared -o fftools/SEINalExtractor.o -fPIC  fftools/SEINalExtractor.cpp

gcc -c -o golomb.o -fPIC libavcodec/golomb.c

gcc -I. -I./ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -I/home/praneet/ffmpeg_build/include -gstabs+ -std=c++11 -pthread  -I/home/praneet/ffmpeg_build/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/freetype2  -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/opus         -DZMQ_BUILD_DRAFT_API=1 -I/usr/local/include -I/usr/include/alsa -c -o h264_parse.o -fPIC libavcodec/h264_parse.c

gcc -I. -I./ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -I/home/praneet/ffmpeg_build/include -gstabs+ -std=c++11 -pthread  -I/home/praneet/ffmpeg_build/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/freetype2  -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/opus         -DZMQ_BUILD_DRAFT_API=1 -I/usr/local/include -I/usr/include/alsa -c -o parser.o -fPIC libavcodec/parser.c

gcc -I. -I./ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -I/home/praneet/ffmpeg_build/include -gstabs+ -std=c++11 -pthread  -I/home/praneet/ffmpeg_build/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/freetype2  -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/opus         -DZMQ_BUILD_DRAFT_API=1 -I/usr/local/include -I/usr/include/alsa -c -o h2645_parse.o -fPIC libavcodec/h2645_parse.c -lstdc++ -Llibavcodec -Llibavdevice -Llibavfilter -Llibavformat -Llibavresample -Llibavutil -Llibpostproc -Llibswscale -Llibswresample -L/home/praneet/ffmpeg_build/lib  -Wl,--as-needed -Wl,-z,noexecstack -Wl,--warn-common -Wl,-rpath-link=libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample -lavdevice -lavfilter -lavformat -lavcodec -lpostproc -lswresample -lswscale -lavutil

gcc -I. -I./ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -I/home/praneet/ffmpeg_build/include -gstabs+ -std=c++11 -pthread  -I/home/praneet/ffmpeg_build/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/freetype2  -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/opus         -DZMQ_BUILD_DRAFT_API=1 -I/usr/local/include -I/usr/include/alsa -c -o h264_sei.o -fPIC golomb.o libavcodec/h264_sei.c -lstdc++ -Llibavcodec -Llibavdevice -Llibavfilter -Llibavformat -Llibavresample -Llibavutil -Llibpostproc -Llibswscale -Llibswresample -L/home/praneet/ffmpeg_build/lib  -Wl,--as-needed -Wl,-z,noexecstack -Wl,--warn-common -Wl,-rpath-link=libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample -lavdevice -lavfilter -lavformat -lavcodec -lpostproc -lswresample -lswscale -lavutil  -lm -lxcb -lXau -lXdmcp -lxcb-shm -lxcb -lXau -lXdmcp -lxcb-shape -lxcb -lXau -lXdmcp -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -lasound -lm -ldl -lpthread -lrt -lSDL2 -Wl,--no-undefined -lm -ldl -lasound -lm -ldl -lpthread -lpulse-simple -lpulse -lsndio -lX11 -lXext -lXcursor -lXinerama -lXi -lXrandr -lXss -lXxf86vm -lwayland-egl -lwayland-client -lwayland-cursor -lxkbcommon -lpthread -lrt -lsndio -lXv -lX11 -lXext -pthread -lm -lva -lass -lm -lharfbuzz -lfontconfig -lexpat -lfreetype -lexpat -lfribidi -lfreetype -lz -lpng12 -lz -lm -L/usr/local/lib -lzmq -lstdc++ -lfreetype -lz -lpng12 -lz -lm -lm -lz -lvpx -lm -lpthread -lvpx -lm -lpthread -lvpx -lm -lpthread -lvpx -lm -lpthread -pthread -lm -llzma -lz -L/home/praneet/ffmpeg_build/lib   -l python3.5m -lboost_python-py35 -lboost_system

gcc -I. -I./ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -I/home/praneet/ffmpeg_build/include -gstabs+ -std=c++11 -pthread  -I/home/praneet/ffmpeg_build/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/freetype2  -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/opus         -DZMQ_BUILD_DRAFT_API=1 -I/usr/local/include -I/usr/include/alsa -c -o h264_ps.o -fPIC golomb.o h264_parse.o parser.o h2645_parse.o h264_sei.o libavcodec/h264_ps.c -lstdc++ -Llibavcodec -Llibavdevice -Llibavfilter -Llibavformat -Llibavresample -Llibavutil -Llibpostproc -Llibswscale -Llibswresample -L/home/praneet/ffmpeg_build/lib  -Wl,--as-needed -Wl,-z,noexecstack -Wl,--warn-common -Wl,-rpath-link=libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample -lavdevice -lavfilter -lavformat -lavcodec -lpostproc -lswresample -lswscale -lavutil  -lm -lxcb -lXau -lXdmcp -lxcb-shm -lxcb -lXau -lXdmcp -lxcb-shape -lxcb -lXau -lXdmcp -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -lasound -lm -ldl -lpthread -lrt -lSDL2 -Wl,--no-undefined -lm -ldl -lasound -lm -ldl -lpthread -lpulse-simple -lpulse -lsndio -lX11 -lXext -lXcursor -lXinerama -lXi -lXrandr -lXss -lXxf86vm -lwayland-egl -lwayland-client -lwayland-cursor -lxkbcommon -lpthread -lrt -lsndio -lXv -lX11 -lXext -pthread -lm -lva -lass -lm -lharfbuzz -lfontconfig -lexpat -lfreetype -lexpat -lfribidi -lfreetype -lz -lpng12 -lz -lm -L/usr/local/lib -lzmq -lstdc++ -lfreetype -lz -lpng12 -lz -lm -lm -lz -lvpx -lm -lpthread -lvpx -lm -lpthread -lvpx -lm -lpthread -lvpx -lm -lpthread -pthread -lm -llzma -lz -L/home/praneet/ffmpeg_build/lib   -l python3.5m -lboost_python-py35 -lboost_system

gcc -I. -I./ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -I/home/praneet/ffmpeg_build/include -gstabs+ -std=c++11 -pthread  -I/home/praneet/ffmpeg_build/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/freetype2  -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/opus         -DZMQ_BUILD_DRAFT_API=1 -I/usr/local/include -I/usr/include/alsa -c -o mathtables.o -fPIC libavcodec/mathtables.c

gcc -I. -I./ -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DZLIB_CONST -I/home/praneet/ffmpeg_build/include -gstabs+ -std=c++11 -pthread  -I/home/praneet/ffmpeg_build/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/fribidi -I/usr/include/freetype2  -I/usr/include/freetype2 -I/usr/include/opus -I/usr/include/opus         -DZMQ_BUILD_DRAFT_API=1 -I/usr/local/include -I/usr/include/alsa -c -o h264data.o -fPIC libavcodec/h264data.c

gcc fftools/SEINalExtractor.o h264data.o mathtables.o golomb.o h264_ps.o h264_parse.o parser.o h2645_parse.o h264_sei.o -lstdc++ -Llibavcodec -Llibavdevice -Llibavfilter -Llibavformat -Llibavresample -Llibavutil -Llibpostproc -Llibswscale -Llibswresample -L/home/praneet/ffmpeg_build/lib  -Wl,--as-needed -Wl,-z,noexecstack -Wl,--warn-common -Wl,-rpath-link=libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample -lavdevice -lavfilter -lavformat -lavcodec -lpostproc -lswresample -lswscale -lavutil  -lm -lxcb -lXau -lXdmcp -lxcb-shm -lxcb -lXau -lXdmcp -lxcb-shape -lxcb -lXau -lXdmcp -lxcb-xfixes -lxcb-render -lxcb-shape -lxcb -lXau -lXdmcp -lasound -lm -ldl -lpthread -lrt -lSDL2 -Wl,--no-undefined -lm -ldl -lasound -lm -ldl -lpthread -lpulse-simple -lpulse -lsndio -lX11 -lXext -lXcursor -lXinerama -lXi -lXrandr -lXss -lXxf86vm -lwayland-egl -lwayland-client -lwayland-cursor -lxkbcommon -lpthread -lrt -lsndio -lXv -lX11 -lXext -pthread -lm -lva -lass -lm -lharfbuzz -lfontconfig -lexpat -lfreetype -lexpat -lfribidi -lfreetype -lz -lpng12 -lz -lm -L/usr/local/lib -lzmq -lstdc++ -lfreetype -lz -lpng12 -lz -lm -lm -lz -lvpx -lm -lpthread -lvpx -lm -lpthread -lvpx -lm -lpthread -lvpx -lm -lpthread -pthread -lm -llzma -lz -L/home/praneet/ffmpeg_build/lib   -l python3.5m -lboost_python-py35 -lboost_system -w  `pkg-config --cflags --libs opencv` -shared -o SEINalExtractor.so




